from enum import Enum

class MemoryType(str, Enum):
    INJURY_REPORT = "INJURY_REPORT"          # ✅ CORRIGÉ
    LIFE_CONSTRAINT = "LIFE_CONSTRAINT"      # ✅ CORRIGÉ
    STRATEGIC_OVERRIDE = "STRATEGIC_OVERRIDE" # ✅ CORRIGÉ
    BIOFEEDBACK_LOG = "BIOFEEDBACK_LOG"      # ✅ CORRIGÉ (Remplace PREFERENCE/OTHER)

class ImpactLevel(str, Enum):
    SEVERE = "SEVERE"      # ✅ CORRIGÉ (Remplace HIGH)
    MODERATE = "MODERATE"  # ✅ CORRIGÉ (Remplace MEDIUM)
    INFO = "INFO"          # ✅ CORRIGÉ (Remplace LOW)

class MemoryStatus(str, Enum):
    ACTIVE = "ACTIVE"
    RESOLVED = "RESOLVED"
    ARCHIVED = "ARCHIVED"
    FORGOTTEN = "FORGOTTEN"

class FeedItemType(str, Enum):
    INFO = "INFO"
    ANALYSIS = "ANALYSIS"
    ACTION = "ACTION"
    ALERT = "ALERT"
    WORKOUT_LOG = "WORKOUT_LOG"
    COACH_INSIGHT = "COACH_INSIGHT"
    PERSONAL_RECORD = "PERSONAL_RECORD"
    SYSTEM_ALERT = "SYSTEM_ALERT"
    DAILY_TIP = "DAILY_TIP"

class SportType(str, Enum):
    RUGBY = "Rugby"
    FOOTBALL = "Football"
    CROSSFIT = "CrossFit"
    HYBRID = "Hybrid"
    RUNNING = "Running"
    OTHER = "Autre"
    BODYBUILDING = "BODYBUILDING"
    CYCLING = "CYCLING"
    TRIATHLON = "TRIATHLON"
    POWERLIFTING = "POWERLIFTING"
    SWIMMING = "SWIMMING"
    COMBAT_SPORTS = "COMBAT_SPORTS"

class EquipmentType(str, Enum):
    PERFORMANCE_LAB = "PERFORMANCE_LAB"
    COMMERCIAL_GYM = "COMMERCIAL_GYM"
    HOME_GYM_BARBELL = "HOME_GYM_BARBELL"
    HOME_GYM_DUMBBELL = "HOME_GYM_DUMBBELL"
    CALISTHENICS_KIT = "CALISTHENICS_KIT"
    BODYWEIGHT_ZERO = "BODYWEIGHT_ZERO"
    ENDURANCE_SUITE = "ENDURANCE_SUITE"
    STANDARD = "Standard"
    HOME_GYM_FULL = "HOME_GYM_FULL"
    CROSSFIT_BOX = "CROSSFIT_BOX"
    DUMBBELLS = "DUMBBELLS"
    BARBELL = "BARBELL"
    KETTLEBELLS = "KETTLEBELLS"
    PULL_UP_BAR = "PULL_UP_BAR"
    BENCH = "BENCH"
    DIP_STATION = "DIP_STATION"
    BANDS = "BANDS"
    RINGS_TRX = "RINGS_TRX"
    JUMP_ROPE = "JUMP_ROPE"
    WEIGHT_VEST = "WEIGHT_VEST"
    BIKE = "BIKE"
    HOME_TRAINER = "HOME_TRAINER"
    ROWER = "ROWER"
    TREADMILL = "TREADMILL"
    POOL = "POOL"